name: Local
variables:
  - name: token
    value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTgsInJvbGUiOiJzdHVkZW50IiwiaWF0IjoxNzg5NjYyMjc5LCJleHAiOjE3ODk3NDg2Nzl9.BFLQmvV19ly-_t2RQ-YFR-V0l9MvKwipdF2wQbKfsxo
  - name: studentToken
    value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTgsInJvbGUiOiJzdHVkZW50IiwiaWF0IjoxNzg5NjYyMjc5LCJleHAiOjE3ODk3NDg2Nzl9.BFLQmvV19ly-_t2RQ-YFR-V0l9MvKwipdF2wQbKfsxo
  - name: authorToken
    value: ""
  - name: adminToken
    value: ""
  - name: baseUrl
    value: http://localhost:5000
